[package]
org = "dumindusameendra"
name = "debug_transactional_func_test"
version = "0.1.0"
distribution = "2201.8.2"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
path = "zeroDivision/myapp.jar"

[[platform.java17.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.20"